## Numpy basic and array
learn about numpy with chai aur code


In [1]:
import numpy as np

In [2]:
arr_1d =np.array([1,2,3,4,5])
print("array 1 " ,arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("2d array",arr_2d)


array 1  [1 2 3 4 5]
2d array [[1 2 3]
 [4 5 6]]


In [8]:
py_list=[1,2,3,4]
print('python list multiplication',py_list*2)
np_array=np.array([1,2,3,4])
print(" numpy  array multiplication",np_array*2)


import time
start=time.time()
py_list=[i*2 for i in range(10000000)]
print('\n lsit operatio time ',time.time()-start)

start=time.time()
np_array=np.arange(10000000)
print('\n lsit operatio time ',time.time()-start)


python list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
 numpy  array multiplication [2 4 6 8]

 lsit operatio time  1.2305827140808105

 lsit operatio time  0.056890249252319336


## creating array from scratch


In [21]:
zeros=np.zeros((3,4))
print('zeros array',zeros)

ones=np.ones((2,3))
print("ones array",ones)

full=np.full((3,4),7)
print("full array: \n",full)

random_arr=np.random.random((3,4))

print("random array",random_arr)

sequence=np.arange(0,10,2)
print("sequence array",sequence)



zeros array [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random array [[0.59383643 0.16899721 0.24967456 0.5709623 ]
 [0.9765133  0.70677701 0.45097856 0.15296465]
 [0.37602446 0.5692541  0.3506823  0.50970992]]
sequence array [0 2 4 6 8]


### vector ,matrix and tensor


In [25]:
vector=np.array([1,2,3])
print("vector:",vector) 

matrix=np.array([[1,2,3],
                [4,5,6]])

print("matrix :",matrix)

tesnor=np.array([
                [[1,2],[3,4]],
                [[5,6],[7,8]]
                ])

print('tensor :', tesnor)

vector: [1 2 3]
matrix : [[1 2 3]
 [4 5 6]]
tensor : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array proprty


In [32]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("shape",arr.shape)
print('dimesion',arr.ndim)
print('size',arr.size)
print('data type',arr.dtype)

shape (2, 3)
dimesion 2
size 6
data type int64


## array reshaping


In [ ]:
arr=np.arange(12)
print('orignal array',arr)

reshaped=arr.reshape((3,4))
print("reshape array : \n ",reshaped)

flattend=reshaped.flatten()
print("flatend: \n",flattend)
#return view instead of copy
raveled=reshaped.ravel()
print("raveld:\n",raveled)

#transpose 

tranpose=reshaped.T
print("transpose:\n",tranpose)



orignal array [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape array : 
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatend: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveld:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
