## Numpy array operation


In [1]:
import numpy as np


In [7]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing",arr[2:5])

print("with step",arr[1:8:2])
print("negative indexing",arr[-3])



basic slicing [3 4 5]
with step [2 4 6 8]
negative indexing 8


In [15]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specific element",arr_2d[1,2])
print("whole row: ",arr_2d[1])
print("whole coloum",arr_2d[:,0])

specific element 6
whole row:  [4 5 6]
whole coloum [1 4 7]


## sorting

In [23]:
unsorted=np.array([3,1,4,1,5,9,2,6])
print("sorted array",np.sort(unsorted))

arr_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array by colum",np.sort(arr_2d_unsorted,axis=0))

sorted array [1 1 2 3 4 5 6 9]
sorted 2d array by colum [[1 1]
 [2 2]
 [3 3]]


## filtering

In [26]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=numbers[numbers%2==0]
print("even numbers",even_number)

even numbers [ 2  4  6  8 10]


filter with mask

In [31]:
mask=numbers>5
print("number greater then 5 :",numbers[mask])

number greater then 5 : [ 6  7  8  9 10]


## facny indexing vs np.where()

In [37]:
indices=[0,2,4]
print(numbers[indices])

where_result=np.where(numbers>5)
print("np where",numbers[where_result])

[1 3 5]
np where [ 6  7  8  9 10]


In [48]:
condition_arr=np.where(numbers>5,numbers*2,numbers)
print(condition_arr)


[ 1  2  3  4  5 12 14 16 18 20]


## adding an removing data

In [53]:
arr1=np.array([1,2,3])
arr2=np.array([3,4,5])
combined=np.concatenate((arr1,arr2))
print("combined array",combined)

combined array [1 2 3 3 4 5]


## array compatiblitly

In [54]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

print("compatibleity shape",a.shape==b.shape)

compatibleity shape True


In [60]:
orignal=np.array([[1,2],[3,4],[6,7]])
new_row=np.array([[5,6]])
with_new_row=np.vstack((orignal,new_row))

print(orignal)
print(with_new_row)

new_col=np.array([[7],[8],[9]])
with_new_col=np.hstack((orignal,new_col))
print(with_new_col)

[[1 2]
 [3 4]
 [6 7]]
[[1 2]
 [3 4]
 [6 7]
 [5 6]]
[[1 2 7]
 [3 4 8]
 [6 7 9]]


In [67]:
arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,2)
print("array after deletion",deleted)

array after deletion [1 2 4 5]
